/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sumador.h"
#include <stdio.h>
#include <unistd.h>

bool_t
vmaxmin_1_svc(iarray *argp, numbers_result *result, struct svc_req *rqstp)
{
	bool_t retval;
	numbers_result resultado;
	int i;
	
	resultado.max = -1;
	resultado.min=99999999;
	if(argp->iarray_len > 0){
		printf("\nSolicitud: buscar en una serie de %d números el máximo y mínimo\n", argp->iarray_len);
		for (i=0;i<argp->iarray_len;i++){
			if(argp->iarray_val[i] < resultado.min)
				resultado.min = argp->iarray_val[i];
			
			if(argp->iarray_val[i] > resultado.max)
				resultado.max = argp->iarray_val[i];
		}
				retval=TRUE;
	}
	printf("\n---------------Fin de la búsqueda---------------------\n");
	*result = resultado;
	return retval;
}

bool_t
suma_1_svc(id_number *argp, int *result, struct svc_req *rqstp)
{
	bool_t retval;
	
	if(argp->value){
		*result = argp->old_value + argp->value;
		retval=TRUE;
	}
	printf("\nSolicitud proceso %d sumar '%d + %d'\n", argp->pID, argp->old_value, argp->value);
	//sleep(3);
	return retval;
}

int
sumador_maxmin_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
