/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sumador.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#include <wait.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

pthread_t p_thread;
pthread_attr_t attr;

/* Ejecutada por cada hilo */
void *
execute(void *data)
{
	struct thr_data
	{
		struct svc_req *rqstp;
		SVCXPRT *transp;
	} *ptr_data;
	
	union {
		iarray vmaxmin_1_arg;
		id_number suma_1_arg;
	} argument;
	union {
		numbers_result vmaxmin_1_res;
		int suma_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);
	
	ptr_data = (struct thr_data *)data;
	struct svc_req *rqstp = ptr_data->rqstp;
	register SVCXPRT *transp = ptr_data->transp;
	
	switch (rqstp->rq_proc) {
		case NULLPROC:
			(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
			exit(0);

		case VMAXMIN:
			_xdr_argument = (xdrproc_t) xdr_iarray;
			_xdr_result = (xdrproc_t) xdr_numbers_result;
			local = (bool_t (*) (char *, void *,  struct svc_req *))vmaxmin_1_svc;
			break;

		case SUMA:
			sleep(2);
			_xdr_argument = (xdrproc_t) xdr_id_number;
			_xdr_result = (xdrproc_t) xdr_int;
			local = (bool_t (*) (char *, void *,  struct svc_req *))suma_1_svc;
			break;

		default:
			svcerr_noproc (transp);
			return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		exit(1);
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!sumador_maxmin_prog_1_freeresult (transp, _xdr_result, (caddr_t) &result)){
		fprintf (stderr, "%s", "unable to free results");
		exit(1);
	}
	exit(0);
}

/* 
	Wrapper para proveer concurrencia a nivel hilos 
	en el servidor 
*/

static void
sumador_concurrente_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	/* Estructura que usa el hilo para ejecutar */
	struct data_str
	{
		struct svc_req *rqstp;
		SVCXPRT *transp;
	} *data_ptr=(struct data_str*)malloc(sizeof(struct data_str));
	
	data_ptr->rqstp = rqstp;
	data_ptr->transp = transp;
	/* Crea y lanza el hilo */
	pthread_attr_setdetachstate(&attr,PTHREAD_CREATE_DETACHED);
	pthread_create(&p_thread,&attr,execute,(void *)data_ptr);
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;
	pmap_unset (SUMADOR_MAXMIN_PROG, SUMADOR_MAXMIN_VERSION);
	
	/* Registro el wrapper concurrente	*/
	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SUMADOR_MAXMIN_PROG, SUMADOR_MAXMIN_VERSION, sumador_concurrente_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SUMADOR_MAXMIN_PROG, SUMADOR_MAXMIN_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SUMADOR_MAXMIN_PROG, SUMADOR_MAXMIN_VERSION, sumador_concurrente_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SUMADOR_MAXMIN_PROG, SUMADOR_MAXMIN_VERSION, tcp).");
		exit(1);
	}
	printf("\n------------------------------------------------------\n\n");
	printf("\n   Se inicia el Servidor   ");
	printf("\n\n------------------------------------------------------\n\n");
	
	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
