/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sumador.h"
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include <sys/types.h>
#include <unistd.h>

CLIENT *clnt;

void connect_rpc(char * host)
{
  //Conecta con el servidor rpc
  
  #ifndef DEBUG
    clnt = clnt_create (host, SUMADOR_MAXMIN_PROG, SUMADOR_MAXMIN_VERSION, "tcp");
    if (clnt == NULL) {
      clnt_pcreateerror (host);
      exit (1);
    }
    printf("\nSe conecta con el servidor\n");
  #endif  /* DEBUG */
}

void disconnect_rpc()
{
  //Desconecta con el servidor rpc
  
  #ifndef DEBUG
    clnt_destroy (clnt);
    printf("\nSe desconecta con el servidor\n");
  #endif  /* DEBUG */
}

void
execute(int *values, int n)
{
	enum clnt_stat retval_1;
	numbers_result result_1;
	iarray  numbers;
	
	enum clnt_stat retval_2;
	int result_2;
	id_number  suma_1_arg;
	
	int i;
	
	/* Seteo de iarray para mandar al servidor */
  	numbers.iarray_len = n;
  	numbers.iarray_val = values;
	
	suma_1_arg.old_value = 0;
	
	/* Calculo de la suma total */
	for (i=0;i<n;i++){ 
		suma_1_arg.value = values[i];
		suma_1_arg.pID = getpid();
		retval_2 = suma_1(&suma_1_arg, &result_2, clnt);
		if (retval_2 != RPC_SUCCESS) {
			clnt_perror (clnt, "call failed");
		}
		suma_1_arg.old_value = result_2;
	}
	
	printf("\nLa suma total es: %d\n", result_2);
	
	/* Calculo del máximo y el mínimo */
	
	retval_1 = vmaxmin_1(&numbers, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("\nEl máximo en la lista es %d y el mínimo es %d\n", result_1.max, result_1.min);
	
}

int
main (int argc, char *argv[])
{
	char *host;
	int *ints,n;
	int i;
	
	if (argc < 3) {
		printf ("Usar: %s server_host num1 num2 ...\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	/* Obtengo los argumentos */
	n = argc-2;
  	ints = (int *) malloc(n * sizeof( int ));
	if (ints==NULL) {
		fprintf(stderr,"Error alocando memoria\n");
		exit(0);
  	}
	for (i=2;i<argc;i++) {
    	ints[i-2] = atoi(argv[i]);
  	}
	
	printf("\nSe comienza con el programa, conectandose al host: %s", host);
	connect_rpc(host);	
	execute(ints, n);
	disconnect_rpc();
	exit (0);
}
