/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sumador.h"

bool_t
xdr_numbers_result (XDR *xdrs, numbers_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_id_number (XDR *xdrs, id_number *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->old_value))
		 return FALSE;
	 if (!xdr_pid_t (xdrs, &objp->pID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_iarray (XDR *xdrs, iarray *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->iarray_val, (u_int *) &objp->iarray_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
